add_lunch_combo omni_m5c-userdebug

export ALLOW_MISSING_DEPENDENCIES=true
export FOX_REPLACE_TOOLBOX_GETPROP=1
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export LC_ALL="C"
export OF_LEGACY_SHAR512=1
